spring:
  profiles:
    active: dev

  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

my-env:
  first: dd
  second: 5678