spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

my-env:
  first: ${FIRST_BYUNGIL_ENV}
  second: ${SECOND_BYUNGIL_ENV}